import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "de" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Top Bar Navigation
    "nav.topbar.press": "Presse",
    "nav.topbar.statutes": "Satzung",
    "nav.topbar.donate": "Spenden",
    "nav.topbar.contact": "Kontakt",
    
    // Main Navigation
    "nav.policy": "Policy",
    "nav.policy.readPapers": "Positionspapiere lesen",
    "nav.events": "Veranstaltungen",
    "nav.events.upcoming": "Kommende Events",
    "nav.events.apply": "Jetzt bewerben",
    "nav.digitalHub": "Digital Hub",
    "nav.digitalHub.about": "Über den Hub",
    "nav.digitalHub.apply": "Jetzt bewerben",
    "nav.roadshow": "Roadshow",
    "nav.roadshow.request": "Roadshow anfragen",
    "nav.login": "Anmelden",
    "nav.register": "Registrieren",
    "nav.dashboard": "Dashboard",
    "nav.myDashboard": "Mein Dashboard",
    "nav.myApplications": "Meine Bewerbungen",
    "nav.profileSettings": "Profileinstellungen",
    "nav.logout": "Abmelden",
    
    // Home - Hero
    "home.hero.slogan": "Für eine chancengerechte, nachhaltige und zukunftsfähige Bildung für alle",
    "home.hero.coreStatement": "Wir verbinden Politik und Innovation",
    "home.hero.thinkTankDescription": "Als unabhängiger Think Tank bringen wir politische Vision und innovative Lösungen durch gezielten Dialog zusammen",
    "home.hero.exploreVision": "Unsere Vision entdecken",
    "home.hero.joinInnovation": "Innovation Area beitreten",
    
    // Home - Three Pillars
    "home.pillars.title": "Unsere drei Säulen",
    "home.pillars.policy.title": "Policy Papers & Vision",
    "home.pillars.policy.description": "Positionspapiere, die unser Bildungssystem in die Zukunft führen",
    "home.pillars.policy.button": "Positionspapiere lesen",
    "home.pillars.events.title": "Events & Roadshows",
    "home.pillars.events.description": "Wir bringen Bildungsinnovatoren und politische Entscheidungsträger in moderierten, kuratierten Umgebungen zusammen",
    "home.pillars.events.button": "Events ansehen",
    "home.pillars.hub.title": "Digital Hub",
    "home.pillars.hub.description": "Wir bieten den digitalen Raum, in dem sich alle Beteiligten registrieren, informieren und Bildungsinnovationen entdecken können",
    "home.pillars.hub.button": "Zum Hub",
    
    // Home - Roadshow
    "home.roadshow.valueProposition": "Von der Anfrage zur Präsentation in 2-3 Wochen – wir kümmern uns um alles.",
    "home.roadshow.label": "Innovation Area On Demand",
    "home.roadshow.title": "Bringen Sie die Innovation Area zu Ihrer Veranstaltung",
    "home.roadshow.description": "Städte, Kommunen und Konferenzen können unsere kuratierte Innovationsschau als Komplettpaket buchen",
    "home.roadshow.benefit1": "Kuratierte Auswahl von 5-6 Bildungsinnovatoren",
    "home.roadshow.benefit2": "Professioneller Aufbau und Moderation",
    "home.roadshow.benefit3": "Auf Ihre Schwerpunkte zugeschnitten",
    "home.roadshow.button": "Roadshow anfragen",
    
    // Home - Logo Sections
    "home.logos.ministries.title": "Für wen wir arbeiten",
    "home.logos.partners.title": "Unsere Partner und Verbände",
    "home.logos.supporters.title": "Unsere Unterstützer",
    "home.logos.supporters.subtitle": "Wir sind öffentlich und spendenfinanziert. Wir bedanken uns bei zahlreichen Unterstützern, vielen Einzelspendern und insbesondere bei unseren institutionellen Förderern:",
    
    // Partners Section
    "partners.statesTitle": "Unsere Adressaten",
    "partners.statesSubtitle": "Wir arbeiten mit allen 16 Bundesländern und dem BMBF zusammen, um digitale Bildung voranzutreiben",
    "partners.partnersTitle": "Verbände und Partner",
    "partners.cta.title": "Werden Sie Teil unserer Mission",
    "partners.cta.description": "Gemeinsam gestalten wir die Zukunft der digitalen Bildung in Deutschland",
    "partners.cta.button": "Jetzt bewerben",
    
    // Home - CTA
    "home.cta.title": "Bereit zum Entdecken?",
    "home.cta.description": "Entdecken Sie unsere Veranstaltungen, durchstöbern Sie Innovationen oder erfahren Sie, wie Sie Teil der Innovation Area werden",
    "home.cta.viewEvents": "Veranstaltungen",
    "home.cta.browseInnovations": "Innovationen",
    "home.cta.howToApply": "So bewerben",
    
    // Policy Page
    "policy.title": "Policy Übersicht",
    "policy.subtitle": "Unsere Positionspapiere und Medienbeiträge zur Zukunft der digitalen Bildung",
    "policy.filter.all": "Alle anzeigen",
    "policy.filter.position": "Positionspapiere",
    "policy.filter.press": "Presseauftritte",
    "policy.type.position": "Positionspapier",
    "policy.type.press": "Presseauftritt",
    "policy.download": "Herunterladen",
    "policy.readMore": "Weiterlesen",
    "policy.noResults": "Keine Einträge gefunden",
    "policy.cta.title": "Interesse an unserer Arbeit?",
    "policy.cta.description": "Kontaktieren Sie uns für Medienanfragen, Kooperationen oder weitere Informationen zu unseren Positionen.",
    "policy.cta.button": "Kontakt aufnehmen",
    
    // Events Page
    "events.title": "Innovation Area Events",
    "events.subtitle": "Erleben Sie die Innovation Area auf unseren Veranstaltungen in ganz Deutschland, wo Bildungsinnovatoren und Entscheidungsträger in kuratierten, moderierten Settings zusammenkommen.",
    "events.section.open": "Offene Anmeldungen",
    "events.section.open.description": "Bewerben Sie sich jetzt für diese Events. Bewerbungsfrist: 31. Januar 2026.",
    "events.section.future": "Zukünftige Veranstaltungen",
    "events.section.future.description": "Diese Events sind geplant. Die Bewerbungsphase beginnt am 1. Mai 2026.",
    "events.section.past": "Vergangene Events",
    "events.section.past.description": "Erfolgreiche Innovation Area Events aus der Vergangenheit.",
    "events.status.open": "Bewerbung offen",
    "events.status.comingSoon": "Demnächst",
    "events.status.completed": "Abgeschlossen",
    "events.round1": "Runde 1",
    "events.round2": "Runde 2",
    "events.deadline": "Bewerbungsfrist",
    "events.applyNow": "Jetzt bewerben",
    "events.learnMore": "Mehr erfahren",
    "events.viewRecap": "Rückblick ansehen",
    "events.registrationOpens": "Anmeldung startet",
    "events.cta.title": "Möchten Sie teilnehmen?",
    "events.cta.description": "Präsentieren Sie Ihre Innovation auf unseren kommenden Events und treten Sie in Dialog mit Bildungsexperten, Institutionen und Entscheidungsträgern in ganz Deutschland.",
    "events.sponsorAcknowledgment": "Die Innovation Area Roadmap 2026 ist finanziell gesichert durch unsere Sponsoren: Cancom und Inventorio",

    // Innovations Page
    "innovations.title": "Innovationen entdecken",
    "innovations.search": "Nach Innovationen suchen...",
    "innovations.allCategories": "Alle Kategorien",
    "innovations.allRegions": "Alle Regionen",
    "innovations.allTechnologies": "Alle Technologien",
    "innovations.clearFilters": "Filter zurücksetzen",
    "innovations.showing": "Zeige",
    "innovations.innovations": "Innovationen",
    "innovations.innovation": "Innovation",

    // Roadshow Page
    "roadshow.hero.title": "Innovation Area Roadshow",
    "roadshow.hero.subtitle": "Bringen Sie die Innovation Area zu Ihrer Veranstaltung – kuratierte Bildungsinnovationen, professionell präsentiert",
    "roadshow.hero.button": "Jetzt anfragen",
    "roadshow.what.title": "Was ist die Roadshow?",
    "roadshow.what.description": "Die Innovation Area Roadshow bringt eine kuratierte Auswahl digitaler Bildungsinnovationen direkt zu Ihrer Veranstaltung. Wir übernehmen die komplette Organisation – von der Auswahl passender Innovatoren bis zum professionellen Aufbau vor Ort.",
    "roadshow.why.title": "Warum die Roadshow buchen?",
    "roadshow.why.curated.title": "Kuratierte Auswahl",
    "roadshow.why.curated.description": "Wir wählen 5-6 passende Bildungsinnovatoren aus unserem Netzwerk, abgestimmt auf Ihre Zielgruppe und Schwerpunkte.",
    "roadshow.why.professional.title": "Professionelle Umsetzung",
    "roadshow.why.professional.description": "Kompletter Service inklusive Aufbau, Moderation und Betreuung – Sie können sich auf Ihre Gäste konzentrieren.",
    "roadshow.why.impact.title": "Maximale Wirkung",
    "roadshow.why.impact.description": "Interaktive Präsentationen und moderierte Dialoge sorgen für echten Austausch zwischen Innovatoren und Entscheidungsträgern.",
    "roadshow.who.title": "Für wen ist die Roadshow?",
    "roadshow.who.cities.title": "Städte & Kommunen",
    "roadshow.who.cities.description": "Zeigen Sie Ihren Bürgern und Schulen, welche digitalen Bildungslösungen verfügbar sind.",
    "roadshow.who.conferences.title": "Konferenzen & Tagungen",
    "roadshow.who.conferences.description": "Bereichern Sie Ihre Veranstaltung mit einer interaktiven Innovationsausstellung.",
    "roadshow.who.fairs.title": "Bildungsmessen",
    "roadshow.who.fairs.description": "Ergänzen Sie Ihr Messeprogramm mit kuratierten Showcases zukunftsweisender EdTech-Lösungen.",
    "roadshow.how.title": "So funktioniert es",
    "roadshow.how.step1.title": "Anfrage senden",
    "roadshow.how.step1.description": "Füllen Sie unser Formular aus und teilen Sie uns Ihre Anforderungen und Wunschtermin mit.",
    "roadshow.how.step2.title": "Beratungsgespräch",
    "roadshow.how.step2.description": "Wir besprechen Ihre Ziele und stimmen die Auswahl der Innovatoren auf Ihre Zielgruppe ab.",
    "roadshow.how.step3.title": "Planung & Vorbereitung",
    "roadshow.how.step3.description": "Wir koordinieren alle Innovatoren, bereiten die Präsentationen vor und planen den Aufbau.",
    "roadshow.how.step4.title": "Durchführung",
    "roadshow.how.step4.description": "Am Veranstaltungstag übernehmen wir Aufbau, Moderation und Betreuung – Sie lehnen sich zurück.",
    "roadshow.confirmation.title": "Anfrage erhalten!",
    "roadshow.confirmation.description": "Vielen Dank für Ihre Anfrage. Wir melden uns innerhalb von 2-3 Werktagen bei Ihnen.",
    "roadshow.confirmation.inquiryId": "Ihre Anfrage-ID:",
    "roadshow.confirmation.returnHome": "Zur Startseite",
    "roadshow.confirmation.viewEvents": "Events ansehen",
    "roadshow.toast.agreementRequired": "Zustimmung erforderlich",
    "roadshow.toast.agreementDescription": "Bitte stimmen Sie der Kontaktaufnahme zu.",
    "roadshow.toast.dateRequired": "Datum erforderlich",
    "roadshow.toast.dateDescription": "Bitte wählen Sie ein Veranstaltungsdatum aus.",
    "roadshow.toast.submitted": "Anfrage gesendet",
    "roadshow.toast.submittedDescription": "Wir haben Ihre Anfrage erhalten und melden uns in Kürze.",
    "roadshow.form.title": "Roadshow anfragen",
    "roadshow.form.orgType": "Organisationstyp",
    "roadshow.form.orgType.placeholder": "Bitte wählen",
    "roadshow.form.orgType.city": "Stadt / Kommune",
    "roadshow.form.orgType.conference": "Konferenz / Tagung",
    "roadshow.form.orgType.fair": "Messe / Ausstellung",
    "roadshow.form.orgType.district": "Landkreis / Bezirk",
    "roadshow.form.orgType.other": "Sonstiges",
    "roadshow.form.orgName": "Name der Organisation",
    "roadshow.form.contactName": "Ansprechpartner",
    "roadshow.form.email": "E-Mail",
    "roadshow.form.phone": "Telefon",
    "roadshow.form.eventDetails": "Veranstaltungsdetails",
    "roadshow.form.eventName": "Name der Veranstaltung",
    "roadshow.form.eventDate": "Veranstaltungsdatum",
    "roadshow.form.eventDate.placeholder": "Datum auswählen",
    "roadshow.form.eventLocation": "Veranstaltungsort",
    "roadshow.form.eventLocation.placeholder": "Stadt, Venue",
    "roadshow.form.expectedAttendees": "Erwartete Teilnehmerzahl",
    "roadshow.form.eventType": "Art der Veranstaltung",
    "roadshow.form.eventType.placeholder": "Bitte wählen",
    "roadshow.form.eventType.conference": "Konferenz",
    "roadshow.form.eventType.fair": "Messe",
    "roadshow.form.eventType.municipal": "Kommunale Veranstaltung",
    "roadshow.form.eventType.other": "Sonstiges",
    "roadshow.form.focusAreas": "Thematische Schwerpunkte",
    "roadshow.form.focusAreas.hint": "Welche Themen interessieren Ihre Zielgruppe besonders?",
    "roadshow.form.focusAreas.k12": "Schule (K-12)",
    "roadshow.form.focusAreas.higher": "Hochschule",
    "roadshow.form.focusAreas.teacher": "Lehrerfortbildung",
    "roadshow.form.focusAreas.leadership": "Schulleitung & Verwaltung",
    "roadshow.form.focusAreas.tech": "Technologie & Infrastruktur",
    "roadshow.form.focusAreas.other": "Sonstiges",
    "roadshow.form.specialRequirements": "Besondere Anforderungen",
    "roadshow.form.specialRequirements.placeholder": "Gibt es besondere Wünsche oder Anforderungen?",
    "roadshow.form.budget": "Budgetrahmen",
    "roadshow.form.budget.placeholder": "Bitte wählen",
    "roadshow.form.budget.under5k": "Unter 5.000 €",
    "roadshow.form.budget.5k10k": "5.000 - 10.000 €",
    "roadshow.form.budget.10k20k": "10.000 - 20.000 €",
    "roadshow.form.budget.over20k": "Über 20.000 €",
    "roadshow.form.budget.discuss": "Möchte ich besprechen",
    "roadshow.form.howDidYouHear": "Wie haben Sie von uns erfahren?",
    "roadshow.form.agreeToContact": "Ich bin damit einverstanden, dass das ZDB-Team mich bezüglich dieser Anfrage kontaktiert.",
    "roadshow.form.submitting": "Wird gesendet...",
    "roadshow.form.submit": "Anfrage senden",
    "roadshow.faq.title": "Häufig gestellte Fragen",
    "roadshow.faq.q1": "Wie viel kostet die Roadshow?",
    "roadshow.faq.a1": "Die Kosten hängen von Größe und Umfang ab. Ein typisches Paket mit 5-6 Innovatoren liegt zwischen 5.000 und 15.000 €. Gerne erstellen wir Ihnen ein individuelles Angebot.",
    "roadshow.faq.q2": "Wie viel Vorlaufzeit benötigt ihr?",
    "roadshow.faq.a2": "Idealerweise 8-12 Wochen, um die passenden Innovatoren zu koordinieren. Bei kürzerer Vorlaufzeit sprechen Sie uns gerne an – wir finden eine Lösung.",
    "roadshow.faq.q3": "Wie viel Platz wird benötigt?",
    "roadshow.faq.a3": "Für ein Standard-Setup mit 5-6 Innovatoren empfehlen wir mindestens 100m². Wir passen das Format aber gerne an Ihre Räumlichkeiten an.",
    "roadshow.faq.q4": "Kann ich bestimmte Innovatoren anfragen?",
    "roadshow.faq.a4": "Ja, natürlich! Wenn Sie bestimmte Innovatoren aus unserem Netzwerk kennen, berücksichtigen wir Ihre Wünsche bei der Zusammenstellung.",

    // Footer
    "footer.aboutTitle": "Über ZDB Innovation Area",
    "footer.description": "Gestaltung der Zukunft der digitalen Bildung in Deutschland durch strategische Vision und kuratierte Verbindungen.",
    "footer.quickLinks": "Schnelllinks",
    "footer.contact": "Kontakt",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.policy": "Policy",
    
    // Nav (used in Footer)
    "nav.innovations": "Innovationen",
    "nav.howToApply": "So bewerben",

    // Language identifier
    "language": "de",

    // Press Page
    "press.title": "Presse",
    "press.subtitle": "Pressemitteilungen, Medienanfragen und Pressekit",
    "press.contact.title": "Pressekontakt",
    "press.contact.description": "Für Medienanfragen und Interviewwünsche stehen wir Ihnen gerne zur Verfügung.",
    "press.releases.title": "Pressemitteilungen",
    "press.download": "Herunterladen",
    "press.kit.title": "Pressekit",
    "press.kit.description": "Laden Sie unser Pressekit mit Logos, Fotos und Hintergrundinformationen herunter.",
    "press.kit.download": "Pressekit herunterladen",

    // Statutes Page
    "statutes.title": "Satzung",
    "statutes.subtitle": "Die rechtlichen Grundlagen und Organisation des ZDB e.V.",
    "statutes.downloadPdf": "Satzung als PDF herunterladen",
    "statutes.section.purpose.title": "Zweck und Ziele",
    "statutes.section.purpose.content": "Der Verein verfolgt ausschließlich und unmittelbar gemeinnützige Zwecke. Zweck des Vereins ist die Förderung von Bildung und Wissenschaft, insbesondere im Bereich der digitalen Bildung.",
    "statutes.section.membership.title": "Mitgliedschaft",
    "statutes.section.membership.content": "Mitglied des Vereins kann jede natürliche oder juristische Person werden, die die Ziele des Vereins unterstützt. Die Mitgliedschaft wird durch schriftlichen Antrag und Aufnahme durch den Vorstand erworben.",
    "statutes.section.organization.title": "Organe des Vereins",
    "statutes.section.organization.content": "Die Organe des Vereins sind die Mitgliederversammlung, der Vorstand und der Beirat. Die Mitgliederversammlung ist das oberste Organ des Vereins.",
    "statutes.section.governance.title": "Vorstand",
    "statutes.section.governance.content": "Der Vorstand besteht aus dem Vorsitzenden, dem stellvertretenden Vorsitzenden und dem Schatzmeister. Der Vorstand wird von der Mitgliederversammlung für die Dauer von drei Jahren gewählt.",
    "statutes.legal.title": "Rechtliche Informationen",
    "statutes.legal.content": "Der ZDB e.V. ist ein eingetragener gemeinnütziger Verein mit Sitz in Berlin.",
    "statutes.legal.registration": "Registernummer",
    "statutes.legal.court": "Registergericht",

    // Donate Page
    "donate.title": "Spenden",
    "donate.subtitle": "Unterstützen Sie unsere Mission für bessere digitale Bildung in Deutschland",
    "donate.impact.title": "Ihre Spende bewirkt",
    "donate.impact.innovation.title": "Innovation fördern",
    "donate.impact.innovation.description": "Ermöglichen Sie EdTech-Startups den Zugang zu Entscheidungsträgern und fördern Sie innovative Bildungslösungen.",
    "donate.impact.community.title": "Gemeinschaft stärken",
    "donate.impact.community.description": "Verbinden Sie Bildungsinnovatoren, Schulen und Politik für einen nachhaltigen Dialog.",
    "donate.impact.events.title": "Events ermöglichen",
    "donate.impact.events.description": "Unterstützen Sie unsere Roadshows und Events, die Innovation und Politik zusammenbringen.",
    "donate.options.title": "Spendenoptionen",
    "donate.bank.title": "Überweisung",
    "donate.bank.description": "Spenden Sie bequem per Banküberweisung:",
    "donate.bank.recipient": "Empfänger",
    "donate.bank.reference": "Verwendungszweck",
    "donate.online.title": "Online-Spende",
    "donate.online.description": "Spenden Sie schnell und sicher online mit PayPal oder Kreditkarte.",
    "donate.online.button": "Jetzt online spenden",
    "donate.tax.title": "Steuerlich absetzbar",
    "donate.tax.description": "Als gemeinnütziger Verein stellen wir Ihnen gerne eine Spendenquittung aus. Ihre Spende ist steuerlich absetzbar.",

    // Contact Page
    "contact.title": "Kontakt",
    "contact.subtitle": "Haben Sie Fragen? Wir freuen uns auf Ihre Nachricht.",
    "contact.info.title": "Kontaktinformationen",
    "contact.info.address.label": "Adresse",
    "contact.info.email.label": "E-Mail",
    "contact.info.phone.label": "Telefon",
    "contact.info.hours.label": "Öffnungszeiten",
    "contact.info.hours.weekdays": "Mo-Fr: 9:00 - 17:00 Uhr",
    "contact.info.hours.weekend": "Sa-So: Geschlossen",
    "contact.form.title": "Schreiben Sie uns",
    "contact.form.firstName": "Vorname",
    "contact.form.lastName": "Nachname",
    "contact.form.email": "E-Mail",
    "contact.form.subject": "Betreff",
    "contact.form.message": "Nachricht",
    "contact.form.submit": "Nachricht senden",
    "contact.form.sending": "Wird gesendet...",
    "contact.form.success.title": "Nachricht gesendet",
    "contact.form.success.description": "Vielen Dank für Ihre Nachricht. Wir melden uns schnellstmöglich bei Ihnen.",

    // Profile Page
    "profile.title": "Profil bearbeiten",
    "profile.backToDashboard": "Zurück zum Dashboard",
    "profile.role.innovator": "Innovator",
    "profile.role.admin": "Administrator",
    "profile.role.politician": "Politiker",
    "profile.company.title": "Unternehmensinformationen",
    "profile.company.description": "Informationen zu Ihrem Unternehmen oder Ihrer Organisation",
    "profile.contact.title": "Kontaktdaten",
    "profile.contact.description": "Ihre Kontaktinformationen für Rückfragen",
    "profile.form.companyName": "Unternehmensname",
    "profile.form.contactPerson": "Ansprechpartner",
    "profile.form.email": "E-Mail",
    "profile.form.website": "Website",
    "profile.form.description": "Kurzbeschreibung",
    "profile.form.descriptionPlaceholder": "Beschreiben Sie Ihr Unternehmen oder Ihre Innovation...",
    "profile.save": "Speichern",
    "profile.saving": "Wird gespeichert...",
    "profile.save.success.title": "Profil gespeichert",
    "profile.save.success.description": "Ihre Änderungen wurden erfolgreich gespeichert.",

    // Dashboard Page
    "dashboard.welcome": "Willkommen zurück",
    "dashboard.subtitle": "Verwalten Sie Ihre Bewerbungen und verfolgen Sie Ihren Weg in der Innovation Area",
    "dashboard.stats.totalApplications": "Bewerbungen gesamt",
    "dashboard.stats.pendingReview": "In Prüfung",
    "dashboard.stats.upcomingEvents": "Kommende Events",
    "dashboard.myApplications": "Meine Bewerbungen",
    "dashboard.noApplications": "Sie haben noch keine Bewerbungen eingereicht",
    "dashboard.applyNow": "Jetzt bewerben",
    "dashboard.applyToNewEvent": "Für neues Event bewerben",
    "dashboard.applied": "Beworben",
    "dashboard.viewDetails": "Details ansehen",
    "dashboard.quickActions": "Schnellaktionen",
    "dashboard.editProfile": "Profil bearbeiten",
    "dashboard.viewAllEvents": "Alle Events ansehen",
    "dashboard.browseInnovations": "Innovationen durchsuchen",
    "dashboard.recommendedEvents": "Empfohlene Events",
    "dashboard.apply": "Bewerben",
    "dashboard.roadshowInquiries": "Roadshow-Anfragen",
    "dashboard.event": "Event",
    "dashboard.submitted": "Eingereicht",
    "dashboard.fullDetails": "Vollständige Details",
    "dashboard.exportData": "Daten exportieren",
    "dashboard.status.submitted": "Eingereicht",
    "dashboard.status.underReview": "In Prüfung",
    "dashboard.status.selected": "Ausgewählt",
    "dashboard.status.notSelected": "Nicht ausgewählt",
    "dashboard.roadshow.status.new": "Neu",
    "dashboard.roadshow.status.inDiscussion": "In Bearbeitung",
    "dashboard.roadshow.status.confirmed": "Bestätigt",
    "dashboard.roadshow.status.completed": "Abgeschlossen",
    "dashboard.roadshow.status.declined": "Abgelehnt",

    // NotFound Page
    "notFound.title": "Seite nicht gefunden",
    "notFound.description": "Die von Ihnen gesuchte Seite existiert leider nicht oder wurde verschoben.",
    "notFound.returnHome": "Zur Startseite",
    "notFound.browseInnovations": "Innovationen durchsuchen",
    "notFound.goBack": "Zurück",

    // Signup Modal
    "signup.title": "Registrierungsanfrage",
    "signup.description": "Um Teil der Innovation Area zu werden, senden Sie uns zunächst eine Registrierungsanfrage. Nach Prüfung durch unser Team erhalten Sie Zugang zur Bewerbungsplattform.",
    "signup.form.role": "Rolle",
    "signup.form.selectRole": "Rolle auswählen",
    "signup.form.roleHint": "Wählen Sie Ihre Rolle in der Plattform",
    "signup.role.innovator": "Innovator / EdTech-Unternehmen",
    "signup.role.politician": "Politiker / Entscheidungsträger",
    "signup.form.companyName": "Unternehmensname / Organisation",
    "signup.form.companyNamePlaceholder": "Ihr Unternehmen GmbH",
    "signup.form.contactPerson": "Ansprechpartner",
    "signup.form.contactPersonPlaceholder": "Max Mustermann",
    "signup.form.email": "E-Mail-Adresse",
    "signup.form.emailPlaceholder": "kontakt@unternehmen.de",
    "signup.form.website": "Website",
    "signup.form.description": "Kurzbeschreibung",
    "signup.form.descriptionPlaceholder": "Beschreiben Sie kurz Ihre EdTech-Lösung bzw. Ihr Interesse an der Plattform...",
    "signup.form.characters": "Zeichen",
    "signup.form.agreeTerms": "Ich stimme den Nutzungsbedingungen und der Datenschutzerklärung zu",
    "signup.form.submit": "Anfrage absenden",
    "signup.error.title": "Fehler",
    "signup.error.note": "Hinweis",
    "signup.error.requiredFields": "Bitte füllen Sie alle Pflichtfelder aus",
    "signup.error.invalidEmail": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    "signup.error.agreeTerms": "Sie müssen den Nutzungsbedingungen und der Datenschutzerklärung zustimmen",
    "signup.error.emailExists": "Eine Anfrage mit dieser E-Mail-Adresse existiert bereits",
    "signup.success.title": "Anfrage eingereicht!",
    "signup.success.description": "Vielen Dank für Ihre Registrierungsanfrage. Unser Team wird Ihre Angaben prüfen und sich innerhalb von 5-7 Werktagen bei Ihnen melden.",
    "signup.success.nextSteps": "Nächste Schritte:",
    "signup.success.step1": "Unser Team prüft Ihre Anfrage",
    "signup.success.step2": "Bei Genehmigung erhalten Sie eine E-Mail mit Zugangsdaten",
    "signup.success.step3": "Nach dem Login können Sie sich für Events bewerben",
    "signup.close": "Schließen",
  },
  en: {
    // Top Bar Navigation
    "nav.topbar.press": "Press",
    "nav.topbar.statutes": "Statutes",
    "nav.topbar.donate": "Donate",
    "nav.topbar.contact": "Contact",
    
    // Main Navigation
    "nav.policy": "Policy",
    "nav.policy.readPapers": "Read Position Papers",
    "nav.events": "Events",
    "nav.events.upcoming": "Upcoming Events",
    "nav.events.apply": "Apply Now",
    "nav.digitalHub": "Digital Hub",
    "nav.digitalHub.about": "About Hub",
    "nav.digitalHub.apply": "Apply Now",
    "nav.roadshow": "Roadshow",
    "nav.roadshow.request": "Request a Roadshow",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.dashboard": "Dashboard",
    "nav.myDashboard": "My Dashboard",
    "nav.myApplications": "My Applications",
    "nav.profileSettings": "Profile Settings",
    "nav.logout": "Logout",
    
    // Home - Hero
    "home.hero.slogan": "For equitable, sustainable, and future-ready education for all",
    "home.hero.coreStatement": "We Connect Politics and Innovation",
    "home.hero.thinkTankDescription": "As an independent think tank, we bring policy vision and innovative solutions together through targeted dialogue",
    "home.hero.exploreVision": "Explore Our Vision",
    "home.hero.joinInnovation": "Join the Innovation Area",

    // Home - Three Pillars
    "home.pillars.title": "Our Three Pillars",
    "home.pillars.policy.title": "Policy Papers & Vision",
    "home.pillars.policy.description": "Position papers that guide our education system into the future",
    "home.pillars.policy.button": "Read Position Papers",
    "home.pillars.events.title": "Events & Roadshows",
    "home.pillars.events.description": "We bring together education innovators and policy-makers in moderated, curated settings",
    "home.pillars.events.button": "View Events",
    "home.pillars.hub.title": "Digital Hub",
    "home.pillars.hub.description": "We provide the digital space where all stakeholders can register, stay informed, and discover education innovations",
    "home.pillars.hub.button": "Go to Hub",
    
    // Home - Roadshow
    "home.roadshow.valueProposition": "From inquiry to showcase in 2-3 weeks—we handle everything.",
    "home.roadshow.label": "Innovation Area On Demand",
    "home.roadshow.title": "Bring the Innovation Area to Your Event",
    "home.roadshow.description": "Cities, municipalities, and conferences can book our curated innovation showcase as a complete package",
    "home.roadshow.benefit1": "Curated selection of 5-6 education innovators",
    "home.roadshow.benefit2": "Professional setup and moderation",
    "home.roadshow.benefit3": "Customized to your focus areas",
    "home.roadshow.button": "Request a Roadshow",
    
    // Home - Logo Sections
    "home.logos.ministries.title": "Who We Work For",
    "home.logos.partners.title": "Our Partners and Associations",
    "home.logos.supporters.title": "Our Supporters",
    "home.logos.supporters.subtitle": "We are publicly and donation-funded. We thank our many supporters, individual donors, and especially our institutional sponsors:",
    
    // Partners Section
    "partners.statesTitle": "Our Addressees",
    "partners.statesSubtitle": "We collaborate with all 16 federal states and the BMBF to advance digital education",
    "partners.partnersTitle": "Associations & Partners",
    "partners.cta.title": "Become Part of Our Mission",
    "partners.cta.description": "Together we shape the future of digital education in Germany",
    "partners.cta.button": "Apply Now",
    
    // Home - CTA
    "home.cta.title": "Ready to Explore?",
    "home.cta.description": "Discover our events, browse innovations, or learn how to become part of the Innovation Area",
    "home.cta.viewEvents": "View Events",
    "home.cta.browseInnovations": "Browse Innovations",
    "home.cta.howToApply": "How to Apply",
    
    // Policy Page
    "policy.title": "Policy Overview",
    "policy.subtitle": "Our position papers and media contributions on the future of digital education",
    "policy.filter.all": "Show All",
    "policy.filter.position": "Position Papers",
    "policy.filter.press": "Press Appearances",
    "policy.type.position": "Position Paper",
    "policy.type.press": "Press Appearance",
    "policy.download": "Download",
    "policy.readMore": "Read More",
    "policy.noResults": "No entries found",
    "policy.cta.title": "Interested in Our Work?",
    "policy.cta.description": "Contact us for media inquiries, collaborations, or more information about our positions.",
    "policy.cta.button": "Get in Touch",
    
    // Events Page
    "events.title": "Innovation Area Events",
    "events.subtitle": "Experience the Innovation Area at our events across Germany, where education innovators and decision-makers come together in curated, moderated settings.",
    "events.section.open": "Open Registrations",
    "events.section.open.description": "Apply now for these events. Application deadline: January 31, 2026.",
    "events.section.future": "Future Events",
    "events.section.future.description": "These events are planned. Applications open May 1, 2026.",
    "events.section.past": "Past Events",
    "events.section.past.description": "Successful Innovation Area events from the past.",
    "events.status.open": "Applications Open",
    "events.status.comingSoon": "Coming Soon",
    "events.status.completed": "Completed",
    "events.round1": "Round 1",
    "events.round2": "Round 2",
    "events.deadline": "Deadline",
    "events.applyNow": "Apply Now",
    "events.learnMore": "Learn More",
    "events.viewRecap": "View Recap",
    "events.registrationOpens": "Registration Opens",
    "events.cta.title": "Want to participate?",
    "events.cta.description": "Showcase your innovation at our upcoming events and engage with educators, institutions, and decision-makers across Germany.",
    "events.sponsorAcknowledgment": "The 2026 Innovation Area roadmap is financially secured thanks to our sponsors: Cancom and Inventorio",

    // Innovations Page
    "innovations.title": "Discover Innovations",
    "innovations.search": "Search for innovations...",
    "innovations.allCategories": "All Categories",
    "innovations.allRegions": "All Regions",
    "innovations.allTechnologies": "All Technologies",
    "innovations.clearFilters": "Clear Filters",
    "innovations.showing": "Showing",
    "innovations.innovations": "innovations",
    "innovations.innovation": "innovation",

    // Roadshow Page
    "roadshow.hero.title": "Innovation Area Roadshow",
    "roadshow.hero.subtitle": "Bring the Innovation Area to your event – curated education innovations, professionally presented",
    "roadshow.hero.button": "Request Now",
    "roadshow.what.title": "What is the Roadshow?",
    "roadshow.what.description": "The Innovation Area Roadshow brings a curated selection of digital education innovations directly to your event. We handle the complete organization – from selecting suitable innovators to professional setup on-site.",
    "roadshow.why.title": "Why Book the Roadshow?",
    "roadshow.why.curated.title": "Curated Selection",
    "roadshow.why.curated.description": "We select 5-6 suitable education innovators from our network, tailored to your target audience and focus areas.",
    "roadshow.why.professional.title": "Professional Execution",
    "roadshow.why.professional.description": "Complete service including setup, moderation and support – you can focus on your guests.",
    "roadshow.why.impact.title": "Maximum Impact",
    "roadshow.why.impact.description": "Interactive presentations and moderated dialogues create genuine exchange between innovators and decision-makers.",
    "roadshow.who.title": "Who is the Roadshow For?",
    "roadshow.who.cities.title": "Cities & Municipalities",
    "roadshow.who.cities.description": "Show your citizens and schools what digital education solutions are available.",
    "roadshow.who.conferences.title": "Conferences & Meetings",
    "roadshow.who.conferences.description": "Enrich your event with an interactive innovation exhibition.",
    "roadshow.who.fairs.title": "Education Fairs",
    "roadshow.who.fairs.description": "Complement your fair program with curated showcases of forward-thinking EdTech solutions.",
    "roadshow.how.title": "How It Works",
    "roadshow.how.step1.title": "Submit Request",
    "roadshow.how.step1.description": "Fill out our form and tell us your requirements and preferred date.",
    "roadshow.how.step2.title": "Consultation",
    "roadshow.how.step2.description": "We discuss your goals and coordinate the innovator selection for your target audience.",
    "roadshow.how.step3.title": "Planning & Preparation",
    "roadshow.how.step3.description": "We coordinate all innovators, prepare presentations and plan the setup.",
    "roadshow.how.step4.title": "Execution",
    "roadshow.how.step4.description": "On event day, we handle setup, moderation and support – you sit back and relax.",
    "roadshow.confirmation.title": "Request Received!",
    "roadshow.confirmation.description": "Thank you for your request. We will get back to you within 2-3 business days.",
    "roadshow.confirmation.inquiryId": "Your Request ID:",
    "roadshow.confirmation.returnHome": "Return Home",
    "roadshow.confirmation.viewEvents": "View Events",
    "roadshow.toast.agreementRequired": "Agreement Required",
    "roadshow.toast.agreementDescription": "Please agree to be contacted.",
    "roadshow.toast.dateRequired": "Date Required",
    "roadshow.toast.dateDescription": "Please select an event date.",
    "roadshow.toast.submitted": "Request Submitted",
    "roadshow.toast.submittedDescription": "We have received your request and will be in touch shortly.",
    "roadshow.form.title": "Request Roadshow",
    "roadshow.form.orgType": "Organization Type",
    "roadshow.form.orgType.placeholder": "Please select",
    "roadshow.form.orgType.city": "City / Municipality",
    "roadshow.form.orgType.conference": "Conference / Meeting",
    "roadshow.form.orgType.fair": "Fair / Exhibition",
    "roadshow.form.orgType.district": "District / Region",
    "roadshow.form.orgType.other": "Other",
    "roadshow.form.orgName": "Organization Name",
    "roadshow.form.contactName": "Contact Person",
    "roadshow.form.email": "Email",
    "roadshow.form.phone": "Phone",
    "roadshow.form.eventDetails": "Event Details",
    "roadshow.form.eventName": "Event Name",
    "roadshow.form.eventDate": "Event Date",
    "roadshow.form.eventDate.placeholder": "Select date",
    "roadshow.form.eventLocation": "Event Location",
    "roadshow.form.eventLocation.placeholder": "City, Venue",
    "roadshow.form.expectedAttendees": "Expected Attendees",
    "roadshow.form.eventType": "Event Type",
    "roadshow.form.eventType.placeholder": "Please select",
    "roadshow.form.eventType.conference": "Conference",
    "roadshow.form.eventType.fair": "Fair",
    "roadshow.form.eventType.municipal": "Municipal Event",
    "roadshow.form.eventType.other": "Other",
    "roadshow.form.focusAreas": "Focus Areas",
    "roadshow.form.focusAreas.hint": "Which topics interest your target audience most?",
    "roadshow.form.focusAreas.k12": "K-12 Education",
    "roadshow.form.focusAreas.higher": "Higher Education",
    "roadshow.form.focusAreas.teacher": "Teacher Training",
    "roadshow.form.focusAreas.leadership": "School Leadership & Administration",
    "roadshow.form.focusAreas.tech": "Technology & Infrastructure",
    "roadshow.form.focusAreas.other": "Other",
    "roadshow.form.specialRequirements": "Special Requirements",
    "roadshow.form.specialRequirements.placeholder": "Any special requests or requirements?",
    "roadshow.form.budget": "Budget Range",
    "roadshow.form.budget.placeholder": "Please select",
    "roadshow.form.budget.under5k": "Under €5,000",
    "roadshow.form.budget.5k10k": "€5,000 - €10,000",
    "roadshow.form.budget.10k20k": "€10,000 - €20,000",
    "roadshow.form.budget.over20k": "Over €20,000",
    "roadshow.form.budget.discuss": "Would like to discuss",
    "roadshow.form.howDidYouHear": "How did you hear about us?",
    "roadshow.form.agreeToContact": "I agree to be contacted by the ZDB team regarding this request.",
    "roadshow.form.submitting": "Submitting...",
    "roadshow.form.submit": "Submit Request",
    "roadshow.faq.title": "Frequently Asked Questions",
    "roadshow.faq.q1": "How much does the Roadshow cost?",
    "roadshow.faq.a1": "Costs depend on size and scope. A typical package with 5-6 innovators ranges from €5,000 to €15,000. We're happy to provide a custom quote.",
    "roadshow.faq.q2": "How much lead time do you need?",
    "roadshow.faq.a2": "Ideally 8-12 weeks to coordinate the right innovators. For shorter timelines, please reach out – we'll find a solution.",
    "roadshow.faq.q3": "How much space is required?",
    "roadshow.faq.a3": "For a standard setup with 5-6 innovators, we recommend at least 100m². We can adapt the format to your venue.",
    "roadshow.faq.q4": "Can I request specific innovators?",
    "roadshow.faq.a4": "Yes, of course! If you know specific innovators from our network, we'll consider your preferences when assembling the team.",

    // Footer
    "footer.aboutTitle": "About ZDB Innovation Area",
    "footer.description": "Shaping the future of digital education in Germany through strategic vision and curated connections.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.policy": "Policy",
    
    // Nav (used in Footer)
    "nav.innovations": "Innovations",
    "nav.howToApply": "How to Apply",

    // Language identifier
    "language": "en",

    // Press Page
    "press.title": "Press",
    "press.subtitle": "Press releases, media inquiries, and press kit",
    "press.contact.title": "Press Contact",
    "press.contact.description": "For media inquiries and interview requests, please don't hesitate to contact us.",
    "press.releases.title": "Press Releases",
    "press.download": "Download",
    "press.kit.title": "Press Kit",
    "press.kit.description": "Download our press kit with logos, photos, and background information.",
    "press.kit.download": "Download Press Kit",

    // Statutes Page
    "statutes.title": "Statutes",
    "statutes.subtitle": "The legal foundation and organization of ZDB e.V.",
    "statutes.downloadPdf": "Download Statutes as PDF",
    "statutes.section.purpose.title": "Purpose and Goals",
    "statutes.section.purpose.content": "The association pursues exclusively and directly charitable purposes. The purpose of the association is to promote education and science, particularly in the field of digital education.",
    "statutes.section.membership.title": "Membership",
    "statutes.section.membership.content": "Any natural or legal person who supports the goals of the association can become a member. Membership is acquired through written application and acceptance by the board.",
    "statutes.section.organization.title": "Bodies of the Association",
    "statutes.section.organization.content": "The bodies of the association are the general assembly, the board, and the advisory board. The general assembly is the supreme body of the association.",
    "statutes.section.governance.title": "Board",
    "statutes.section.governance.content": "The board consists of the chairperson, the deputy chairperson, and the treasurer. The board is elected by the general assembly for a term of three years.",
    "statutes.legal.title": "Legal Information",
    "statutes.legal.content": "ZDB e.V. is a registered non-profit association based in Berlin.",
    "statutes.legal.registration": "Registration Number",
    "statutes.legal.court": "Registration Court",

    // Donate Page
    "donate.title": "Donate",
    "donate.subtitle": "Support our mission for better digital education in Germany",
    "donate.impact.title": "Your Donation Makes a Difference",
    "donate.impact.innovation.title": "Support Innovation",
    "donate.impact.innovation.description": "Enable EdTech startups to access decision-makers and promote innovative educational solutions.",
    "donate.impact.community.title": "Strengthen Community",
    "donate.impact.community.description": "Connect education innovators, schools, and policy-makers for sustainable dialogue.",
    "donate.impact.events.title": "Enable Events",
    "donate.impact.events.description": "Support our roadshows and events that bring together innovation and policy.",
    "donate.options.title": "Donation Options",
    "donate.bank.title": "Bank Transfer",
    "donate.bank.description": "Donate conveniently via bank transfer:",
    "donate.bank.recipient": "Recipient",
    "donate.bank.reference": "Reference",
    "donate.online.title": "Online Donation",
    "donate.online.description": "Donate quickly and securely online with PayPal or credit card.",
    "donate.online.button": "Donate Online Now",
    "donate.tax.title": "Tax Deductible",
    "donate.tax.description": "As a non-profit organization, we are happy to provide you with a donation receipt. Your donation is tax deductible.",

    // Contact Page
    "contact.title": "Contact",
    "contact.subtitle": "Have questions? We look forward to hearing from you.",
    "contact.info.title": "Contact Information",
    "contact.info.address.label": "Address",
    "contact.info.email.label": "Email",
    "contact.info.phone.label": "Phone",
    "contact.info.hours.label": "Office Hours",
    "contact.info.hours.weekdays": "Mon-Fri: 9:00 AM - 5:00 PM",
    "contact.info.hours.weekend": "Sat-Sun: Closed",
    "contact.form.title": "Send us a Message",
    "contact.form.firstName": "First Name",
    "contact.form.lastName": "Last Name",
    "contact.form.email": "Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.submit": "Send Message",
    "contact.form.sending": "Sending...",
    "contact.form.success.title": "Message Sent",
    "contact.form.success.description": "Thank you for your message. We will get back to you as soon as possible.",

    // Profile Page
    "profile.title": "Edit Profile",
    "profile.backToDashboard": "Back to Dashboard",
    "profile.role.innovator": "Innovator",
    "profile.role.admin": "Administrator",
    "profile.role.politician": "Politician",
    "profile.company.title": "Company Information",
    "profile.company.description": "Information about your company or organization",
    "profile.contact.title": "Contact Details",
    "profile.contact.description": "Your contact information for inquiries",
    "profile.form.companyName": "Company Name",
    "profile.form.contactPerson": "Contact Person",
    "profile.form.email": "Email",
    "profile.form.website": "Website",
    "profile.form.description": "Short Description",
    "profile.form.descriptionPlaceholder": "Describe your company or innovation...",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.save.success.title": "Profile Saved",
    "profile.save.success.description": "Your changes have been saved successfully.",

    // Dashboard Page
    "dashboard.welcome": "Welcome back",
    "dashboard.subtitle": "Manage your applications and track your Innovation Area journey",
    "dashboard.stats.totalApplications": "Total Applications",
    "dashboard.stats.pendingReview": "Pending Review",
    "dashboard.stats.upcomingEvents": "Upcoming Events",
    "dashboard.myApplications": "My Applications",
    "dashboard.noApplications": "You haven't applied to any events yet",
    "dashboard.applyNow": "Apply Now",
    "dashboard.applyToNewEvent": "Apply to New Event",
    "dashboard.applied": "Applied",
    "dashboard.viewDetails": "View Details",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.editProfile": "Edit My Profile",
    "dashboard.viewAllEvents": "View All Events",
    "dashboard.browseInnovations": "Browse Innovations",
    "dashboard.recommendedEvents": "Upcoming Events You Might Like",
    "dashboard.apply": "Apply",
    "dashboard.roadshowInquiries": "Roadshow Inquiries",
    "dashboard.event": "Event",
    "dashboard.submitted": "Submitted",
    "dashboard.fullDetails": "Full Details",
    "dashboard.exportData": "Export Data",
    "dashboard.status.submitted": "Submitted",
    "dashboard.status.underReview": "Under Review",
    "dashboard.status.selected": "Selected",
    "dashboard.status.notSelected": "Not Selected",
    "dashboard.roadshow.status.new": "New",
    "dashboard.roadshow.status.inDiscussion": "In Discussion",
    "dashboard.roadshow.status.confirmed": "Confirmed",
    "dashboard.roadshow.status.completed": "Completed",
    "dashboard.roadshow.status.declined": "Declined",

    // NotFound Page
    "notFound.title": "Page Not Found",
    "notFound.description": "Sorry, the page you're looking for doesn't exist or has been moved.",
    "notFound.returnHome": "Return Home",
    "notFound.browseInnovations": "Browse Innovations",
    "notFound.goBack": "Go Back",

    // Signup Modal
    "signup.title": "Registration Request",
    "signup.description": "To become part of the Innovation Area, please submit a registration request. After review by our team, you will receive access to the application platform.",
    "signup.form.role": "Role",
    "signup.form.selectRole": "Select a role",
    "signup.form.roleHint": "Choose your role on the platform",
    "signup.role.innovator": "Innovator / EdTech Company",
    "signup.role.politician": "Politician / Decision Maker",
    "signup.form.companyName": "Company Name / Organization",
    "signup.form.companyNamePlaceholder": "Your Company Ltd.",
    "signup.form.contactPerson": "Contact Person",
    "signup.form.contactPersonPlaceholder": "John Doe",
    "signup.form.email": "Email Address",
    "signup.form.emailPlaceholder": "contact@company.com",
    "signup.form.website": "Website",
    "signup.form.description": "Short Description",
    "signup.form.descriptionPlaceholder": "Briefly describe your EdTech solution or your interest in the platform...",
    "signup.form.characters": "characters",
    "signup.form.agreeTerms": "I agree to the Terms of Service and Privacy Policy",
    "signup.form.submit": "Submit Request",
    "signup.error.title": "Error",
    "signup.error.note": "Note",
    "signup.error.requiredFields": "Please fill in all required fields",
    "signup.error.invalidEmail": "Please enter a valid email address",
    "signup.error.agreeTerms": "You must agree to the Terms of Service and Privacy Policy",
    "signup.error.emailExists": "A request with this email address already exists",
    "signup.success.title": "Request Submitted!",
    "signup.success.description": "Thank you for your registration request. Our team will review your information and contact you within 5-7 business days.",
    "signup.success.nextSteps": "Next Steps:",
    "signup.success.step1": "Our team reviews your request",
    "signup.success.step2": "Upon approval, you will receive an email with login credentials",
    "signup.success.step3": "After logging in, you can apply to events",
    "signup.close": "Close",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("language");
    return (stored === "en" || stored === "de") ? stored : "de";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
